Fix compilation error:
radiant\pluginmanager.cpp(2170) : error C2440: '=' : cannot convert from 'epair_t *(__stdcall *)(const char *,const char *)' to 'PFN_QERAPP_ALLOCATEEPAIR'
This conversion requires a reinterpret_cast, a C-style cast or function-style cast